spring:
    profiles:
        default: local

logging:
    level:
        root: INFO
        com.hyunec: DEBUG

jwt:
    secret: ${JWT_SECRET:b3VyLWNsYXNzLWJhbmstYmFja2VuZF9vdXItY2xhc3MtYmFuay1iYWNrZW5k} # todo 환경 변수로 분리
    valid-time: ${JWT_VALID_TIME:1800000}

---
spring.config.activate.on-profile: test

spring:
    ai:
        openai:
            api-key: fill_in_your_openai_api_key_here

---
spring.config.activate.on-profile: local

spring:
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod

